Dif_A <- setdiff(loc_ags,loc_jal)
View(Dif_A)
Dif_A2<- setdiff(loc_ags,loc_zac)
View(Dif_A2)
Dif_A3<- setdiff(loc_ags,mun_jal)
View(Dif_A3)
Dif_A4<- setdiff(loc_ags,mun_zac)
View(Dif_A4)
Dif_A5<- setdiff(mun_ags,loc_jal)
View(Dif_A5)
Dif_A6<- setdiff(mun_ags,loc_zac)
View(Dif_A6)
Dif_A7<- setdiff(mun_ags,mun_jal)
View(Dif_A7)
Dif_A8<- setdiff(mun_ags,mun_zac)
View(Dif_A8)

Co_A1<- intersect(loc_ags,loc_jal)
View(Co_A1)
Co_A2<- intersect(loc_ags,loc_zac)
View(Co_A2)
Co_A3<- intersect(loc_ags,mun_jal)
View(Co_A3)
Co_A4<- intersect(loc_ags,mun_zac)
View(Co_A4)
Co_A5<- intersect(mun_ags,loc_jal)
View(Co_A5)
Co_A6<- intersect(mun_ags,loc_zac)
View(Co_A6)
Co_A7<- intersect(mun_ags,mun_jal)
View(Co_A7)
Co_A8<- intersect(mun_ags,mun_zac)
View(Co_A8)